//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyMessenger.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlyMessenger.Resources.Languages.lang.en-US", typeof(lang_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not activated. Please check your email and activate your account..
        /// </summary>
        public static string accountNotActivated {
            get {
                return ResourceManager.GetString("accountNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You have successfully registered. Please check your email to verify your account..
        /// </summary>
        public static string ACTIVATION_REQUIRED {
            get {
                return ResourceManager.GetString("ACTIVATION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string already_have_account {
            get {
                return ResourceManager.GetString("already-have-account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyone.
        /// </summary>
        public static string anyone {
            get {
                return ResourceManager.GetString("anyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Startup.
        /// </summary>
        public static string autostart {
            get {
                return ResourceManager.GetString("autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklist.
        /// </summary>
        public static string blacklist {
            get {
                return ResourceManager.GetString("blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block user.
        /// </summary>
        public static string block_user {
            get {
                return ResourceManager.GetString("block-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked users.
        /// </summary>
        public static string blocked_users {
            get {
                return ResourceManager.GetString("blocked-users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked users.
        /// </summary>
        public static string blocked_users_second {
            get {
                return ResourceManager.GetString("blocked-users-second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be empty.
        /// </summary>
        public static string cannotBeNull {
            get {
                return ResourceManager.GetString("cannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string chat {
            get {
                return ResourceManager.GetString("chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email with password recovery instructions has been sent to your email..
        /// </summary>
        public static string CHECK_EMAIL {
            get {
                return ResourceManager.GetString("CHECK_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect code..
        /// </summary>
        public static string code_error {
            get {
                return ResourceManager.GetString("code_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversations.
        /// </summary>
        public static string conversations {
            get {
                return ResourceManager.GetString("conversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        public static string copied {
            get {
                return ResourceManager.GetString("copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string copyToClipboard {
            get {
                return ResourceManager.GetString("copyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        public static string delete_acc {
            get {
                return ResourceManager.GetString("delete-acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account?.
        /// </summary>
        public static string delete_acc_question {
            get {
                return ResourceManager.GetString("delete-acc-question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete chat.
        /// </summary>
        public static string delete_chat {
            get {
                return ResourceManager.GetString("delete-chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogues.
        /// </summary>
        public static string dialogues {
            get {
                return ResourceManager.GetString("dialogues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email edit.
        /// </summary>
        public static string edit_email {
            get {
                return ResourceManager.GetString("edit-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name edit.
        /// </summary>
        public static string edit_name {
            get {
                return ResourceManager.GetString("edit-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format..
        /// </summary>
        public static string email_case_error {
            get {
                return ResourceManager.GetString("email-case-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address must be between 3 and 254 characters..
        /// </summary>
        public static string email_error {
            get {
                return ResourceManager.GetString("email_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists..
        /// </summary>
        public static string emailAlreadyTaken {
            get {
                return ResourceManager.GetString("emailAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format..
        /// </summary>
        public static string emailHasIncorrectDomain {
            get {
                return ResourceManager.GetString("emailHasIncorrectDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address must be between 3 and 254 characters..
        /// </summary>
        public static string emailHasIncorrectLength {
            get {
                return ResourceManager.GetString("emailHasIncorrectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format..
        /// </summary>
        public static string emailIsNotValid {
            get {
                return ResourceManager.GetString("emailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format..
        /// </summary>
        public static string emailIsNotValidType {
            get {
                return ResourceManager.GetString("emailIsNotValidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code we sent you by email..
        /// </summary>
        public static string enter_code {
            get {
                return ResourceManager.GetString("enter-code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonian.
        /// </summary>
        public static string estonian {
            get {
                return ResourceManager.GetString("estonian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string forgot_password {
            get {
                return ResourceManager.GetString("forgot-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups and conversations.
        /// </summary>
        public static string g_and_c {
            get {
                return ResourceManager.GetString("g-and-c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string groups {
            get {
                return ResourceManager.GetString("groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide FlyMessenger.
        /// </summary>
        public static string hideWindow {
            get {
                return ResourceManager.GetString("hideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour ago.
        /// </summary>
        public static string hour_ago {
            get {
                return ResourceManager.GetString("hour-ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours ago.
        /// </summary>
        public static string hours_ago {
            get {
                return ResourceManager.GetString("hours-ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password. Check your credentials and try again..
        /// </summary>
        public static string incorrectPassword {
            get {
                return ResourceManager.GetString("incorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your last search history.
        /// </summary>
        public static string last_items {
            get {
                return ResourceManager.GetString("last_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen.
        /// </summary>
        public static string last_seen {
            get {
                return ResourceManager.GetString("last-seen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last action.
        /// </summary>
        public static string lastAction {
            get {
                return ResourceManager.GetString("lastAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname must be at least 3 and not more than 25 characters long..
        /// </summary>
        public static string lastname_error {
            get {
                return ResourceManager.GetString("lastname-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string login_name {
            get {
                return ResourceManager.GetString("login-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to long time ago.
        /// </summary>
        public static string long_time_ago {
            get {
                return ResourceManager.GetString("long-time-ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message forwarding.
        /// </summary>
        public static string message_forwarding {
            get {
                return ResourceManager.GetString("message-forwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string messages {
            get {
                return ResourceManager.GetString("messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string messagesCount {
            get {
                return ResourceManager.GetString("messagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes ago.
        /// </summary>
        public static string minutes_ago {
            get {
                return ResourceManager.GetString("minutes-ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be at least 3 and not more than 25 characters long..
        /// </summary>
        public static string name_error {
            get {
                return ResourceManager.GetString("name-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New device.
        /// </summary>
        public static string new_device {
            get {
                return ResourceManager.GetString("new-device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in from a new device. Please check your email address..
        /// </summary>
        public static string new_device_notification {
            get {
                return ResourceManager.GetString("new-device-notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new device confirmation code is incorrect..
        /// </summary>
        public static string newDeviceCodeIsNotValid {
            get {
                return ResourceManager.GetString("newDeviceCodeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field cannot be empty..
        /// </summary>
        public static string newDeviceCodeIsRequired {
            get {
                return ResourceManager.GetString("newDeviceCodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody.
        /// </summary>
        public static string nobody {
            get {
                return ResourceManager.GetString("nobody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t started talking to anyone yet.
        /// </summary>
        public static string noChats {
            get {
                return ResourceManager.GetString("noChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogs not found.
        /// </summary>
        public static string noDialogs {
            get {
                return ResourceManager.GetString("noDialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No last search history.
        /// </summary>
        public static string noLastItemsFound {
            get {
                return ResourceManager.GetString("noLastItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages not found.
        /// </summary>
        public static string noMessagesFound {
            get {
                return ResourceManager.GetString("noMessagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not now.
        /// </summary>
        public static string not_yet {
            get {
                return ResourceManager.GetString("not-yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string notifications {
            get {
                return ResourceManager.GetString("notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off notifications.
        /// </summary>
        public static string notifications_off {
            get {
                return ResourceManager.GetString("notifications-off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on notifications.
        /// </summary>
        public static string notifications_on {
            get {
                return ResourceManager.GetString("notifications-on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users not found.
        /// </summary>
        public static string noUsers {
            get {
                return ResourceManager.GetString("noUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string online {
            get {
                return ResourceManager.GetString("online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match..
        /// </summary>
        public static string password_case_error {
            get {
                return ResourceManager.GetString("password-case-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 and not more than 32 characters..
        /// </summary>
        public static string password_error {
            get {
                return ResourceManager.GetString("password-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 and not more than 32 characters..
        /// </summary>
        public static string passwordConfirmHasIncorrectLength {
            get {
                return ResourceManager.GetString("passwordConfirmHasIncorrectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 and not more than 32 characters..
        /// </summary>
        public static string passwordHasIncorrectLength {
            get {
                return ResourceManager.GetString("passwordHasIncorrectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string photo {
            get {
                return ResourceManager.GetString("photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string pin {
            get {
                return ResourceManager.GetString("pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string privacy {
            get {
                return ResourceManager.GetString("privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recently.
        /// </summary>
        public static string recently {
            get {
                return ResourceManager.GetString("recently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register to chat with friends!.
        /// </summary>
        public static string register_for_messaging {
            get {
                return ResourceManager.GetString("register-for-messaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string registration {
            get {
                return ResourceManager.GetString("registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string repeat_password {
            get {
                return ResourceManager.GetString("repeat-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat your password.
        /// </summary>
        public static string repeat_your_password {
            get {
                return ResourceManager.GetString("repeat_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the language, need to restart the application..
        /// </summary>
        public static string restart_app {
            get {
                return ResourceManager.GetString("restart-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string russian {
            get {
                return ResourceManager.GetString("russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a chat.
        /// </summary>
        public static string select_chat {
            get {
                return ResourceManager.GetString("select-chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send first message.
        /// </summary>
        public static string send_first_message {
            get {
                return ResourceManager.GetString("send-first-message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session management.
        /// </summary>
        public static string session_management {
            get {
                return ResourceManager.GetString("session-management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sessions.
        /// </summary>
        public static string sessions {
            get {
                return ResourceManager.GetString("sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string sessions_page {
            get {
                return ResourceManager.GetString("sessions-page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show FlyMessenger.
        /// </summary>
        public static string showWindow {
            get {
                return ResourceManager.GetString("showWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string sound {
            get {
                return ResourceManager.GetString("sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off sound.
        /// </summary>
        public static string sound_off {
            get {
                return ResourceManager.GetString("sound-off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on sound.
        /// </summary>
        public static string sound_on {
            get {
                return ResourceManager.GetString("sound-on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on this week.
        /// </summary>
        public static string this_week {
            get {
                return ResourceManager.GetString("this-week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication.
        /// </summary>
        public static string two_step {
            get {
                return ResourceManager.GetString("two-step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two-factor code is incorrect..
        /// </summary>
        public static string twoFactorCodeIsNotValid {
            get {
                return ResourceManager.GetString("twoFactorCodeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field cannot be empty..
        /// </summary>
        public static string twoFactorCodeIsRequired {
            get {
                return ResourceManager.GetString("twoFactorCodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication is not enabled..
        /// </summary>
        public static string twoFactorIsNotEnabled {
            get {
                return ResourceManager.GetString("twoFactorIsNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typing....
        /// </summary>
        public static string typing {
            get {
                return ResourceManager.GetString("typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unabled.
        /// </summary>
        public static string unable {
            get {
                return ResourceManager.GetString("unable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock user.
        /// </summary>
        public static string unblock_user {
            get {
                return ResourceManager.GetString("unblock-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin.
        /// </summary>
        public static string unpin {
            get {
                return ResourceManager.GetString("unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email does not exist..
        /// </summary>
        public static string userDoesNotExist {
            get {
                return ResourceManager.GetString("userDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be at least 3 and not more than 50 characters long..
        /// </summary>
        public static string username_error {
            get {
                return ResourceManager.GetString("username_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email.
        /// </summary>
        public static string username_or_email {
            get {
                return ResourceManager.GetString("username-or-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already taken..
        /// </summary>
        public static string usernameAlreadyTaken {
            get {
                return ResourceManager.GetString("usernameAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be at least 3 and not more than 50 characters long..
        /// </summary>
        public static string usernameHasIncorrectLength {
            get {
                return ResourceManager.GetString("usernameHasIncorrectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or email is already taken..
        /// </summary>
        public static string usernameOrEmailIsTaken {
            get {
                return ResourceManager.GetString("usernameOrEmailIsTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not active. Please check your email for an activation link..
        /// </summary>
        public static string userNotActiveCheckEmail {
            get {
                return ResourceManager.GetString("userNotActiveCheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find an account with that username or email. Please check your credentials and try again..
        /// </summary>
        public static string userNotFound {
            get {
                return ResourceManager.GetString("userNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address to recover your password..
        /// </summary>
        public static string write_email {
            get {
                return ResourceManager.GetString("write-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write message....
        /// </summary>
        public static string writeMessage {
            get {
                return ResourceManager.GetString("writeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string yesterday {
            get {
                return ResourceManager.GetString("yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password.
        /// </summary>
        public static string your_password {
            get {
                return ResourceManager.GetString("your-password", resourceCulture);
            }
        }
    }
}
