//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyMessenger.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlyMessenger.Resources.Languages.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blokeeri kasutaja.
        /// </summary>
        public static string block_user {
            get {
                return ResourceManager.GetString("block-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chatt.
        /// </summary>
        public static string chat {
            get {
                return ResourceManager.GetString("chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chattid.
        /// </summary>
        public static string chats {
            get {
                return ResourceManager.GetString("chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vestlused.
        /// </summary>
        public static string conservations {
            get {
                return ResourceManager.GetString("conservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kustuta vestlus.
        /// </summary>
        public static string delete_chat {
            get {
                return ResourceManager.GetString("delete-chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglise.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eesti.
        /// </summary>
        public static string estonian {
            get {
                return ResourceManager.GetString("estonian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välju.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rühmad.
        /// </summary>
        public static string groups {
            get {
                return ResourceManager.GetString("groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peida FlyMessenger.
        /// </summary>
        public static string hideWindow {
            get {
                return ResourceManager.GetString("hideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keel.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logi välja.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sõnumid.
        /// </summary>
        public static string messagesCount {
            get {
                return ResourceManager.GetString("messagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimi.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teade.
        /// </summary>
        public static string notification {
            get {
                return ResourceManager.GetString("notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teated.
        /// </summary>
        public static string notifications {
            get {
                return ResourceManager.GetString("notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lülitada teateid.
        /// </summary>
        public static string notifications_off {
            get {
                return ResourceManager.GetString("notifications-off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lülita teateid.
        /// </summary>
        public static string notifications_on {
            get {
                return ResourceManager.GetString("notifications-on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinnitada.
        /// </summary>
        public static string pin {
            get {
                return ResourceManager.GetString("pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vene.
        /// </summary>
        public static string russian {
            get {
                return ResourceManager.GetString("russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otsing.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seaded.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Näita FlyMessenger.
        /// </summary>
        public static string showWindow {
            get {
                return ResourceManager.GetString("showWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helis.
        /// </summary>
        public static string sound {
            get {
                return ResourceManager.GetString("sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lülitada heli.
        /// </summary>
        public static string sound_off {
            get {
                return ResourceManager.GetString("sound-off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lülita heli.
        /// </summary>
        public static string sound_on {
            get {
                return ResourceManager.GetString("sound-on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toetus.
        /// </summary>
        public static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        public static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deblokeeri kasutaja.
        /// </summary>
        public static string unblock_user {
            get {
                return ResourceManager.GetString("unblock-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vabastada.
        /// </summary>
        public static string unpin {
            get {
                return ResourceManager.GetString("unpin", resourceCulture);
            }
        }
    }
}
