//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyMessenger.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlyMessenger.Resources.Languages.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teie konto pole aktiveeritud. Kontrollige oma e-posti ja aktiveerige oma konto..
        /// </summary>
        public static string accountNotActivated {
            get {
                return ResourceManager.GetString("accountNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palju õnne! Olete edukalt sisse loginud. Konto kinnitamiseks kontrollige oma meili..
        /// </summary>
        public static string ACTIVATION_REQUIRED {
            get {
                return ResourceManager.GetString("ACTIVATION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On juba konto?.
        /// </summary>
        public static string already_have_account {
            get {
                return ResourceManager.GetString("already-have-account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igaüks saab.
        /// </summary>
        public static string anyone {
            get {
                return ResourceManager.GetString("anyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automaatkäivitus.
        /// </summary>
        public static string autostart {
            get {
                return ResourceManager.GetString("autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must nimekiri.
        /// </summary>
        public static string blacklist {
            get {
                return ResourceManager.GetString("blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blokeeri kasutaja.
        /// </summary>
        public static string block_user {
            get {
                return ResourceManager.GetString("block-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blokeeritud kasutajad.
        /// </summary>
        public static string blocked_users {
            get {
                return ResourceManager.GetString("blocked-users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blokeeritud kasutajaid.
        /// </summary>
        public static string blocked_users_second {
            get {
                return ResourceManager.GetString("blocked-users-second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tühista.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ei saa olla tühi.
        /// </summary>
        public static string cannotBeNull {
            get {
                return ResourceManager.GetString("cannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chatt.
        /// </summary>
        public static string chat {
            get {
                return ResourceManager.GetString("chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teie e-posti aadressile on saadetud e-kiri parooli taastamise juhistega..
        /// </summary>
        public static string CHECK_EMAIL {
            get {
                return ResourceManager.GetString("CHECK_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulge.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kood.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vale kood..
        /// </summary>
        public static string code_error {
            get {
                return ResourceManager.GetString("code_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vestlused.
        /// </summary>
        public static string conversations {
            get {
                return ResourceManager.GetString("conversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopeeritud.
        /// </summary>
        public static string copied {
            get {
                return ResourceManager.GetString("copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopeeri.
        /// </summary>
        public static string copyToClipboard {
            get {
                return ResourceManager.GetString("copyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kustuta.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kustuta konto.
        /// </summary>
        public static string delete_acc {
            get {
                return ResourceManager.GetString("delete-acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kustuta konto?.
        /// </summary>
        public static string delete_acc_question {
            get {
                return ResourceManager.GetString("delete-acc-question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kustuta vestlus.
        /// </summary>
        public static string delete_chat {
            get {
                return ResourceManager.GetString("delete-chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialoogid.
        /// </summary>
        public static string dialogues {
            get {
                return ResourceManager.GetString("dialogues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-poste redigeerimine.
        /// </summary>
        public static string edit_email {
            get {
                return ResourceManager.GetString("edit-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nime redigeerimine.
        /// </summary>
        public static string edit_name {
            get {
                return ResourceManager.GetString("edit-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-post.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kehtetu meilivorming..
        /// </summary>
        public static string email_case_error {
            get {
                return ResourceManager.GetString("email-case-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meiliaadress peab olema 3–254 tähemärgi pikkune..
        /// </summary>
        public static string email_error {
            get {
                return ResourceManager.GetString("email_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-post on juba olemas..
        /// </summary>
        public static string emailAlreadyTaken {
            get {
                return ResourceManager.GetString("emailAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kehtetu meilivorming..
        /// </summary>
        public static string emailHasIncorrectDomain {
            get {
                return ResourceManager.GetString("emailHasIncorrectDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meiliaadress peab olema 3–254 tähemärgi pikkune..
        /// </summary>
        public static string emailHasIncorrectLength {
            get {
                return ResourceManager.GetString("emailHasIncorrectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kehtetu meilivorming..
        /// </summary>
        public static string emailIsNotValid {
            get {
                return ResourceManager.GetString("emailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kehtetu meilivorming..
        /// </summary>
        public static string emailIsNotValidType {
            get {
                return ResourceManager.GetString("emailIsNotValidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglise.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sisestage kood, mille me teile meili teel saatsime..
        /// </summary>
        public static string enter_code {
            get {
                return ResourceManager.GetString("enter-code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eesti.
        /// </summary>
        public static string estonian {
            get {
                return ResourceManager.GetString("estonian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välju.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unustasid parooli?.
        /// </summary>
        public static string forgot_password {
            get {
                return ResourceManager.GetString("forgot-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rühmad ja vestlused.
        /// </summary>
        public static string g_and_c {
            get {
                return ResourceManager.GetString("g-and-c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rühmad.
        /// </summary>
        public static string groups {
            get {
                return ResourceManager.GetString("groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peida FlyMessenger.
        /// </summary>
        public static string hideWindow {
            get {
                return ResourceManager.GetString("hideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tund tagasi.
        /// </summary>
        public static string hour_ago {
            get {
                return ResourceManager.GetString("hour-ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tundi tagasi.
        /// </summary>
        public static string hours_ago {
            get {
                return ResourceManager.GetString("hours-ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vale parool. Kontrollige oma mandaate ja proovige uuesti..
        /// </summary>
        public static string incorrectPassword {
            get {
                return ResourceManager.GetString("incorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keel.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viimati nähtud.
        /// </summary>
        public static string last_seen {
            get {
                return ResourceManager.GetString("last-seen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viimane tegevus.
        /// </summary>
        public static string lastAction {
            get {
                return ResourceManager.GetString("lastAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perekonnanimi.
        /// </summary>
        public static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perekonnanimi peab olema vähemalt 3 ja mitte rohkem kui 25 tähemärki pikk..
        /// </summary>
        public static string lastname_error {
            get {
                return ResourceManager.GetString("lastname-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logi sisse.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasutajanimi.
        /// </summary>
        public static string login_name {
            get {
                return ResourceManager.GetString("login-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logi välja.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kaua aega tagasi.
        /// </summary>
        public static string long_time_ago {
            get {
                return ResourceManager.GetString("long-time-ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sõnumite edastamine.
        /// </summary>
        public static string message_forwarding {
            get {
                return ResourceManager.GetString("message-forwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sõnumid.
        /// </summary>
        public static string messages {
            get {
                return ResourceManager.GetString("messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sõnumid.
        /// </summary>
        public static string messagesCount {
            get {
                return ResourceManager.GetString("messagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutit tagasi.
        /// </summary>
        public static string minutes_ago {
            get {
                return ResourceManager.GetString("minutes-ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimi.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimi peab olema vähemalt 3 ja mitte rohkem kui 25 tähemärki pikk..
        /// </summary>
        public static string name_error {
            get {
                return ResourceManager.GetString("name-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uus seade.
        /// </summary>
        public static string new_device {
            get {
                return ResourceManager.GetString("new-device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olete sisse logitud uuest seadmest. Kontrollige oma e-posti aadressi..
        /// </summary>
        public static string new_device_notification {
            get {
                return ResourceManager.GetString("new-device-notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uue seadme kinnituskood on vale..
        /// </summary>
        public static string newDeviceCodeIsNotValid {
            get {
                return ResourceManager.GetString("newDeviceCodeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Väli ei tohi olla tühi..
        /// </summary>
        public static string newDeviceCodeIsRequired {
            get {
                return ResourceManager.GetString("newDeviceCodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitte keegi.
        /// </summary>
        public static string nobody {
            get {
                return ResourceManager.GetString("nobody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sa pole veel kellegagi rääkima hakanud.
        /// </summary>
        public static string noChats {
            get {
                return ResourceManager.GetString("noChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialoogi ei leitud.
        /// </summary>
        public static string noDialogs {
            get {
                return ResourceManager.GetString("noDialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sõnumeid ei leitud.
        /// </summary>
        public static string noMessagesFound {
            get {
                return ResourceManager.GetString("noMessagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitte praegu.
        /// </summary>
        public static string not_yet {
            get {
                return ResourceManager.GetString("not-yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teated.
        /// </summary>
        public static string notifications {
            get {
                return ResourceManager.GetString("notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lülitada teateid.
        /// </summary>
        public static string notifications_off {
            get {
                return ResourceManager.GetString("notifications-off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lülita teateid.
        /// </summary>
        public static string notifications_on {
            get {
                return ResourceManager.GetString("notifications-on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasutajaid ei leitud.
        /// </summary>
        public static string noUsers {
            get {
                return ResourceManager.GetString("noUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Võrgus.
        /// </summary>
        public static string online {
            get {
                return ResourceManager.GetString("online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parool.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salasõna ei klapi..
        /// </summary>
        public static string password_case_error {
            get {
                return ResourceManager.GetString("password-case-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parool peab olema vähemalt 8 ja mitte rohkem kui 32 tähemärki pikk..
        /// </summary>
        public static string password_error {
            get {
                return ResourceManager.GetString("password-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parool peab olema vähemalt 8 ja mitte rohkem kui 32 tähemärki pikk..
        /// </summary>
        public static string passwordConfirmHasIncorrectLength {
            get {
                return ResourceManager.GetString("passwordConfirmHasIncorrectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parool peab olema vähemalt 8 ja mitte rohkem kui 32 tähemärki pikk..
        /// </summary>
        public static string passwordHasIncorrectLength {
            get {
                return ResourceManager.GetString("passwordHasIncorrectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilt.
        /// </summary>
        public static string photo {
            get {
                return ResourceManager.GetString("photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinnitada.
        /// </summary>
        public static string pin {
            get {
                return ResourceManager.GetString("pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfidentsiaalsus.
        /// </summary>
        public static string privacy {
            get {
                return ResourceManager.GetString("privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiil.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hiljuti.
        /// </summary>
        public static string recently {
            get {
                return ResourceManager.GetString("recently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreeruge sõpradega vestlemiseks!.
        /// </summary>
        public static string register_for_messaging {
            get {
                return ResourceManager.GetString("register-for-messaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreerimine.
        /// </summary>
        public static string registration {
            get {
                return ResourceManager.GetString("registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korda salasõna.
        /// </summary>
        public static string repeat_password {
            get {
                return ResourceManager.GetString("repeat-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korrake oma parooli.
        /// </summary>
        public static string repeat_your_password {
            get {
                return ResourceManager.GetString("repeat_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jah.
        /// </summary>
        public static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keele muutmiseks peab rakenduse taaskäivitama..
        /// </summary>
        public static string restart_app {
            get {
                return ResourceManager.GetString("restart-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vene.
        /// </summary>
        public static string russian {
            get {
                return ResourceManager.GetString("russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvesta.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otsing.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valige vestlus.
        /// </summary>
        public static string select_chat {
            get {
                return ResourceManager.GetString("select-chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saada.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saada esimene sõnum.
        /// </summary>
        public static string send_first_message {
            get {
                return ResourceManager.GetString("send-first-message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seansi juhtimine.
        /// </summary>
        public static string session_management {
            get {
                return ResourceManager.GetString("session-management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seansi.
        /// </summary>
        public static string sessions {
            get {
                return ResourceManager.GetString("sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seansid.
        /// </summary>
        public static string sessions_page {
            get {
                return ResourceManager.GetString("sessions-page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seaded.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Näita FlyMessenger.
        /// </summary>
        public static string showWindow {
            get {
                return ResourceManager.GetString("showWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreeru.
        /// </summary>
        public static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helis.
        /// </summary>
        public static string sound {
            get {
                return ResourceManager.GetString("sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lülitada heli.
        /// </summary>
        public static string sound_off {
            get {
                return ResourceManager.GetString("sound-off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lülita heli.
        /// </summary>
        public static string sound_on {
            get {
                return ResourceManager.GetString("sound-on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toetus.
        /// </summary>
        public static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        public static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sellel nädalal.
        /// </summary>
        public static string this_week {
            get {
                return ResourceManager.GetString("this-week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Täna.
        /// </summary>
        public static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kahefaktoriline autentimine.
        /// </summary>
        public static string two_step {
            get {
                return ResourceManager.GetString("two-step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kahefaktoriline kood on vale..
        /// </summary>
        public static string twoFactorCodeIsNotValid {
            get {
                return ResourceManager.GetString("twoFactorCodeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Väli ei tohi olla tühi..
        /// </summary>
        public static string twoFactorCodeIsRequired {
            get {
                return ResourceManager.GetString("twoFactorCodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kahefaktoriline autentimine pole lubatud..
        /// </summary>
        public static string twoFactorIsNotEnabled {
            get {
                return ResourceManager.GetString("twoFactorIsNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirjutab....
        /// </summary>
        public static string typing {
            get {
                return ResourceManager.GetString("typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Võimatu.
        /// </summary>
        public static string unable {
            get {
                return ResourceManager.GetString("unable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deblokeeri kasutaja.
        /// </summary>
        public static string unblock_user {
            get {
                return ResourceManager.GetString("unblock-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vabastada.
        /// </summary>
        public static string unpin {
            get {
                return ResourceManager.GetString("unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selle e-posti aadressiga kasutajat pole olemas..
        /// </summary>
        public static string userDoesNotExist {
            get {
                return ResourceManager.GetString("userDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasutajanimi.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasutajanimi peab olema vähemalt 3 ja mitte rohkem kui 50 tähemärki pikk..
        /// </summary>
        public static string username_error {
            get {
                return ResourceManager.GetString("username_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasutajanimi või e-post.
        /// </summary>
        public static string username_or_email {
            get {
                return ResourceManager.GetString("username-or-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasutajanimi on juba olemas..
        /// </summary>
        public static string usernameAlreadyTaken {
            get {
                return ResourceManager.GetString("usernameAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasutajanimi peab olema vähemalt 3 ja mitte rohkem kui 50 tähemärki pikk..
        /// </summary>
        public static string usernameHasIncorrectLength {
            get {
                return ResourceManager.GetString("usernameHasIncorrectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasutajanimi või e-posti aadress on juba hõivatud..
        /// </summary>
        public static string usernameOrEmailIsTaken {
            get {
                return ResourceManager.GetString("usernameOrEmailIsTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teie konto pole aktiivne. Kontrollige aktiveerimislingi saamiseks oma meili..
        /// </summary>
        public static string userNotActiveCheckEmail {
            get {
                return ResourceManager.GetString("userNotActiveCheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me ei leidnud selle kasutajanime või e-posti aadressiga kontot. Palun kontrollige oma mandaate ja proovige uuesti..
        /// </summary>
        public static string userNotFound {
            get {
                return ResourceManager.GetString("userNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasutajad.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parooli taastamiseks sisestage oma e-posti aadress..
        /// </summary>
        public static string write_email {
            get {
                return ResourceManager.GetString("write-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirjuta sõnumi....
        /// </summary>
        public static string writeMessage {
            get {
                return ResourceManager.GetString("writeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eile.
        /// </summary>
        public static string yesterday {
            get {
                return ResourceManager.GetString("yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teie parool.
        /// </summary>
        public static string your_password {
            get {
                return ResourceManager.GetString("your-password", resourceCulture);
            }
        }
    }
}
