//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyMessenger.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang_ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_ru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlyMessenger.Resources.Languages.lang.ru-RU", typeof(lang_ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша учетная запись не активирована. Пожалуйста, проверьте свою электронную почту и активируйте учетную запись..
        /// </summary>
        public static string accountNotActivated {
            get {
                return ResourceManager.GetString("accountNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляем! Вы успешно зарегистрировались. Пожалуйста, проверьте свою электронную почту, чтобы подтвердить свой аккаунт..
        /// </summary>
        public static string ACTIVATION_REQUIRED {
            get {
                return ResourceManager.GetString("ACTIVATION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уже есть аккаунт?.
        /// </summary>
        public static string already_have_account {
            get {
                return ResourceManager.GetString("already-have-account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string anyone {
            get {
                return ResourceManager.GetString("anyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автозапуск приложения.
        /// </summary>
        public static string autostart {
            get {
                return ResourceManager.GetString("autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Черный список.
        /// </summary>
        public static string blacklist {
            get {
                return ResourceManager.GetString("blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заблокировать.
        /// </summary>
        public static string block_user {
            get {
                return ResourceManager.GetString("block-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заблокированные пользователи.
        /// </summary>
        public static string blocked_users {
            get {
                return ResourceManager.GetString("blocked-users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заблокированных пользователей.
        /// </summary>
        public static string blocked_users_second {
            get {
                return ResourceManager.GetString("blocked-users-second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не может быть пустым.
        /// </summary>
        public static string cannotBeNull {
            get {
                return ResourceManager.GetString("cannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чат.
        /// </summary>
        public static string chat {
            get {
                return ResourceManager.GetString("chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Письмо с инструкциями по восстановлению пароля отправлено на вашу электронную почту..
        /// </summary>
        public static string CHECK_EMAIL {
            get {
                return ResourceManager.GetString("CHECK_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный код..
        /// </summary>
        public static string code_error {
            get {
                return ResourceManager.GetString("code_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Беседы.
        /// </summary>
        public static string conversations {
            get {
                return ResourceManager.GetString("conversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скопировано.
        /// </summary>
        public static string copied {
            get {
                return ResourceManager.GetString("copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скопировать.
        /// </summary>
        public static string copyToClipboard {
            get {
                return ResourceManager.GetString("copyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить аккаунт.
        /// </summary>
        public static string delete_acc {
            get {
                return ResourceManager.GetString("delete-acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить аккаунт?.
        /// </summary>
        public static string delete_acc_question {
            get {
                return ResourceManager.GetString("delete-acc-question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить чат.
        /// </summary>
        public static string delete_chat {
            get {
                return ResourceManager.GetString("delete-chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диалоги.
        /// </summary>
        public static string dialogues {
            get {
                return ResourceManager.GetString("dialogues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование почты.
        /// </summary>
        public static string edit_email {
            get {
                return ResourceManager.GetString("edit-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование имени.
        /// </summary>
        public static string edit_name {
            get {
                return ResourceManager.GetString("edit-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный формат email..
        /// </summary>
        public static string email_case_error {
            get {
                return ResourceManager.GetString("email-case-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты должен содержать от 3 до 254 символов..
        /// </summary>
        public static string email_error {
            get {
                return ResourceManager.GetString("email_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты уже существует..
        /// </summary>
        public static string emailAlreadyTaken {
            get {
                return ResourceManager.GetString("emailAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный формат email..
        /// </summary>
        public static string emailHasIncorrectDomain {
            get {
                return ResourceManager.GetString("emailHasIncorrectDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты должен содержать от 3 до 254 символов..
        /// </summary>
        public static string emailHasIncorrectLength {
            get {
                return ResourceManager.GetString("emailHasIncorrectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный формат email..
        /// </summary>
        public static string emailIsNotValid {
            get {
                return ResourceManager.GetString("emailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный формат email..
        /// </summary>
        public static string emailIsNotValidType {
            get {
                return ResourceManager.GetString("emailIsNotValidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Английский.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите код, который мы отправили Вам на почту..
        /// </summary>
        public static string enter_code {
            get {
                return ResourceManager.GetString("enter-code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эстонский.
        /// </summary>
        public static string estonian {
            get {
                return ResourceManager.GetString("estonian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыли пароль?.
        /// </summary>
        public static string forgot_password {
            get {
                return ResourceManager.GetString("forgot-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группы и беседы.
        /// </summary>
        public static string g_and_c {
            get {
                return ResourceManager.GetString("g-and-c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группы.
        /// </summary>
        public static string groups {
            get {
                return ResourceManager.GetString("groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть FlyMessenger.
        /// </summary>
        public static string hideWindow {
            get {
                return ResourceManager.GetString("hideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to час назад.
        /// </summary>
        public static string hour_ago {
            get {
                return ResourceManager.GetString("hour-ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to часа(-ов) назад.
        /// </summary>
        public static string hours_ago {
            get {
                return ResourceManager.GetString("hours-ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный пароль. Проверьте свои учетные данные и повторите попытку..
        /// </summary>
        public static string incorrectPassword {
            get {
                return ResourceManager.GetString("incorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История последнего поиска.
        /// </summary>
        public static string last_items {
            get {
                return ResourceManager.GetString("last_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Был(-а) в сети.
        /// </summary>
        public static string last_seen {
            get {
                return ResourceManager.GetString("last-seen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последнее действие.
        /// </summary>
        public static string lastAction {
            get {
                return ResourceManager.GetString("lastAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия должна быть не менее 3 и не более 25 символов..
        /// </summary>
        public static string lastname_error {
            get {
                return ResourceManager.GetString("lastname-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string login_name {
            get {
                return ResourceManager.GetString("login-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to давно.
        /// </summary>
        public static string long_time_ago {
            get {
                return ResourceManager.GetString("long-time-ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пересылка сообщений.
        /// </summary>
        public static string message_forwarding {
            get {
                return ResourceManager.GetString("message-forwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщения.
        /// </summary>
        public static string messages {
            get {
                return ResourceManager.GetString("messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщений.
        /// </summary>
        public static string messagesCount {
            get {
                return ResourceManager.GetString("messagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to минут назад.
        /// </summary>
        public static string minutes_ago {
            get {
                return ResourceManager.GetString("minutes-ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя должно быть не менее 3 и не более 25 символов..
        /// </summary>
        public static string name_error {
            get {
                return ResourceManager.GetString("name-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое устройство.
        /// </summary>
        public static string new_device {
            get {
                return ResourceManager.GetString("new-device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы зашли с нового устройства. Пожалуйста, проверьте Ваш адрес электронной почты..
        /// </summary>
        public static string new_device_notification {
            get {
                return ResourceManager.GetString("new-device-notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код подтверждения нового устройства неверен..
        /// </summary>
        public static string newDeviceCodeIsNotValid {
            get {
                return ResourceManager.GetString("newDeviceCodeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не может быть пустым..
        /// </summary>
        public static string newDeviceCodeIsRequired {
            get {
                return ResourceManager.GetString("newDeviceCodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Никто.
        /// </summary>
        public static string nobody {
            get {
                return ResourceManager.GetString("nobody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы пока не с кем не общались.
        /// </summary>
        public static string noChats {
            get {
                return ResourceManager.GetString("noChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диалоги не найдены.
        /// </summary>
        public static string noDialogs {
            get {
                return ResourceManager.GetString("noDialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История последнего поиска отсутствует.
        /// </summary>
        public static string noLastItemsFound {
            get {
                return ResourceManager.GetString("noLastItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщения не найдены.
        /// </summary>
        public static string noMessagesFound {
            get {
                return ResourceManager.GetString("noMessagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не сейчас.
        /// </summary>
        public static string not_yet {
            get {
                return ResourceManager.GetString("not-yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомления.
        /// </summary>
        public static string notifications {
            get {
                return ResourceManager.GetString("notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключить уведомления.
        /// </summary>
        public static string notifications_off {
            get {
                return ResourceManager.GetString("notifications-off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включить уведомления.
        /// </summary>
        public static string notifications_on {
            get {
                return ResourceManager.GetString("notifications-on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи не найдены.
        /// </summary>
        public static string noUsers {
            get {
                return ResourceManager.GetString("noUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В сети.
        /// </summary>
        public static string online {
            get {
                return ResourceManager.GetString("online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не совпадает..
        /// </summary>
        public static string password_case_error {
            get {
                return ResourceManager.GetString("password-case-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен быть не менее 8 и не более 32 символов..
        /// </summary>
        public static string password_error {
            get {
                return ResourceManager.GetString("password-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен быть не менее 8 и не более 32 символов..
        /// </summary>
        public static string passwordConfirmHasIncorrectLength {
            get {
                return ResourceManager.GetString("passwordConfirmHasIncorrectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен быть не менее 8 и не более 32 символов..
        /// </summary>
        public static string passwordHasIncorrectLength {
            get {
                return ResourceManager.GetString("passwordHasIncorrectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фотография.
        /// </summary>
        public static string photo {
            get {
                return ResourceManager.GetString("photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрепить.
        /// </summary>
        public static string pin {
            get {
                return ResourceManager.GetString("pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конфиденциальность.
        /// </summary>
        public static string privacy {
            get {
                return ResourceManager.GetString("privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to недавно.
        /// </summary>
        public static string recently {
            get {
                return ResourceManager.GetString("recently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрируйтесь, чтобы общаться с друзьями!.
        /// </summary>
        public static string register_for_messaging {
            get {
                return ResourceManager.GetString("register-for-messaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string registration {
            get {
                return ResourceManager.GetString("registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите пароль.
        /// </summary>
        public static string repeat_password {
            get {
                return ResourceManager.GetString("repeat-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите свой пароль.
        /// </summary>
        public static string repeat_your_password {
            get {
                return ResourceManager.GetString("repeat_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ок.
        /// </summary>
        public static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для смены языка придётся перезагрузить приложение..
        /// </summary>
        public static string restart_app {
            get {
                return ResourceManager.GetString("restart-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string russian {
            get {
                return ResourceManager.GetString("russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите чат.
        /// </summary>
        public static string select_chat {
            get {
                return ResourceManager.GetString("select-chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправь первое сообщение.
        /// </summary>
        public static string send_first_message {
            get {
                return ResourceManager.GetString("send-first-message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление сеансами.
        /// </summary>
        public static string session_management {
            get {
                return ResourceManager.GetString("session-management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сеансов.
        /// </summary>
        public static string sessions {
            get {
                return ResourceManager.GetString("sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сеансы.
        /// </summary>
        public static string sessions_page {
            get {
                return ResourceManager.GetString("sessions-page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать FlyMessenger.
        /// </summary>
        public static string showWindow {
            get {
                return ResourceManager.GetString("showWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звук.
        /// </summary>
        public static string sound {
            get {
                return ResourceManager.GetString("sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключить звук.
        /// </summary>
        public static string sound_off {
            get {
                return ResourceManager.GetString("sound-off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включить звук.
        /// </summary>
        public static string sound_on {
            get {
                return ResourceManager.GetString("sound-on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поддержка.
        /// </summary>
        public static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема.
        /// </summary>
        public static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на этой неделе.
        /// </summary>
        public static string this_week {
            get {
                return ResourceManager.GetString("this-week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сегодня.
        /// </summary>
        public static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двухфакторная аутентификация.
        /// </summary>
        public static string two_step {
            get {
                return ResourceManager.GetString("two-step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двухфакторный код неверный..
        /// </summary>
        public static string twoFactorCodeIsNotValid {
            get {
                return ResourceManager.GetString("twoFactorCodeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не может быть пустым..
        /// </summary>
        public static string twoFactorCodeIsRequired {
            get {
                return ResourceManager.GetString("twoFactorCodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двухфакторная аутентификация не включена..
        /// </summary>
        public static string twoFactorIsNotEnabled {
            get {
                return ResourceManager.GetString("twoFactorIsNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печатает....
        /// </summary>
        public static string typing {
            get {
                return ResourceManager.GetString("typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недоступно.
        /// </summary>
        public static string unable {
            get {
                return ResourceManager.GetString("unable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разблокировать.
        /// </summary>
        public static string unblock_user {
            get {
                return ResourceManager.GetString("unblock-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открепить.
        /// </summary>
        public static string unpin {
            get {
                return ResourceManager.GetString("unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким адресом электронной почты не существует..
        /// </summary>
        public static string userDoesNotExist {
            get {
                return ResourceManager.GetString("userDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя должно быть не менее 3 и не более 50 символов..
        /// </summary>
        public static string username_error {
            get {
                return ResourceManager.GetString("username_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользовятеля или email.
        /// </summary>
        public static string username_or_email {
            get {
                return ResourceManager.GetString("username-or-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя уже занято..
        /// </summary>
        public static string usernameAlreadyTaken {
            get {
                return ResourceManager.GetString("usernameAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя должно быть не менее 3 и не более 50 символов..
        /// </summary>
        public static string usernameHasIncorrectLength {
            get {
                return ResourceManager.GetString("usernameHasIncorrectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя или электронная почта уже заняты..
        /// </summary>
        public static string usernameOrEmailIsTaken {
            get {
                return ResourceManager.GetString("usernameOrEmailIsTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш аккаунт не активен. Пожалуйста, проверьте свою электронную почту на наличие ссылки для активации..
        /// </summary>
        public static string userNotActiveCheckEmail {
            get {
                return ResourceManager.GetString("userNotActiveCheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы не смогли найти учетную запись с таким именем пользователя или адресом электронной почты. Проверьте свои учетные данные и повторите попытку..
        /// </summary>
        public static string userNotFound {
            get {
                return ResourceManager.GetString("userNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите свой адрес электронной почты, чтобы восстановить пароль..
        /// </summary>
        public static string write_email {
            get {
                return ResourceManager.GetString("write-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Написать сообщение....
        /// </summary>
        public static string writeMessage {
            get {
                return ResourceManager.GetString("writeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вчера.
        /// </summary>
        public static string yesterday {
            get {
                return ResourceManager.GetString("yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль.
        /// </summary>
        public static string your_password {
            get {
                return ResourceManager.GetString("your-password", resourceCulture);
            }
        }
    }
}
